name: Build and deploy to GitHub Pages

on:
  push:
    branches: [main]

env:
  REACT_APP_USERNAME: teenrage865500690
  REACT_APP_PASSWORD: nma0t2stkcis2vgvpsn0pg91ed
  REACT_APP_CURRENCY_URL: https://xecdapi.xe.com/v1/currencies
  REACT_APP_COUNTRIES_URL: https://restcountries.com/v3.1/all
  REACT_APP_CONVERSTION_URL: https://xecdapi.xe.com/v1/convert_from?
  REACT_APP_CURRENCY_HOUR_URL: https://xecdapi.xe.com/v1/historic_rate/period?

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install, lint, build 🔧
        run: |
          npm install
          npm run lint:js
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
